
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS ROG
 */
public class AplikasiKonversiSuhu extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiKonversiSuhu
     */
    public AplikasiKonversiSuhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        SatuanComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("APLIKASI KONVERSI SUHU");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setText("Masukkan NIlai Suhu  :");

        jLabel3.setText("Hasil Konversi             : ");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jButton1.setText("PROSES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("KELUAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Fahrenheit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jRadioButton1, gridBagConstraints);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Reamur");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jRadioButton2, gridBagConstraints);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Kelvin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jRadioButton3, gridBagConstraints);

        SatuanComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Satuan Suhu", "Celcius", "Fahrenheit", "Reamur", "Kelvin" }));
        SatuanComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SatuanComboBox1ItemStateChanged(evt);
            }
        });
        SatuanComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SatuanComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton1)
                        .addGap(0, 0, 0)
                        .addComponent(jButton2))
                    .addComponent(SatuanComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(SatuanComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addGap(94, 94, 94))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double suhuAwal,hasil;
        hasil = 0;
        suhuAwal = Double.parseDouble(jTextField1.getText());
        
        if (jRadioButton1.isSelected()) {
            if (jRadioButton1.getText().contains("Celcius ke  Fahrenheit ")) {
                hasil= suhuAwal*9/5+32;
            }else if (jRadioButton1.getText().contains("Fahrenheit ke  Celcius ")) {
                hasil = (suhuAwal-32)*5/9;
            }else if (jRadioButton1.getText().contains("Reamur ke  Celcius ")) {
                hasil = suhuAwal*5/4;
            }else if (jRadioButton1.getText().contains("Kelvin ke  Celcius")) {
                hasil = suhuAwal-2731.15;
            }
            
        }else if (jRadioButton2.isSelected()) {
            if (jRadioButton2.getText().contains("Celcius ke  Reamur ")) {
                hasil= suhuAwal*4/5;
            }else if (jRadioButton2.getText().contains("Fahrenheit ke  Reamur ")) {
                hasil = (suhuAwal-32)*4/9;
            }else if (jRadioButton2.getText().contains("Reamur ke  Fahrenheit ")) {
                hasil = suhuAwal*9/4+32;
            }else if (jRadioButton2.getText().contains("Kelvin ke  Fahrenheit")) {
                hasil = (suhuAwal-273.15)*9/5+32;
            }
        }else if (jRadioButton3.isSelected()) {
             if (jRadioButton3.getText().contains("Celcius ke  Kelvin")) {
                hasil= suhuAwal+273.15;
            }else if (jRadioButton3.getText().contains("Fahrenheit ke  Kelvin ")) {
                hasil = (suhuAwal-32)*5/9+273.15;
            }else if (jRadioButton3.getText().contains("Reamur ke  Kelvin ")) {
                hasil = suhuAwal*5/4+273.15;
            }else if (jRadioButton3.getText().contains("Kelvin ke  Reamur")) {
                hasil = (suhuAwal-273.15)*4/5;
            }
            
        }
        
        jTextField2.setText(String.format("%.2f",hasil));
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
       try {
            char c = evt.getKeyChar();
       if (!Character.isDigit(c)){
       evt.consume();
       }
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Hanya Menerima Angka", "Error", JOptionPane.ERROR_MESSAGE);
                    }   
    }//GEN-LAST:event_jTextField1KeyTyped

    private void SatuanComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SatuanComboBox1ActionPerformed
        // TODO add your handling code here:
        SatuanComboBox1.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                String pilihUnit= (String) SatuanComboBox1.getSelectedItem();
                updateRadioButtons(pilihUnit);
                jLabel2.setText("Masukkan NIlai Suhu "+ pilihUnit +" : ");
            }
        
        });
        updateRadioButtons((String) SatuanComboBox1.getSelectedItem());
    }//GEN-LAST:event_SatuanComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        jTextField1.addKeyListener(new KeyAdapter(){
        @Override
        public void keyTyped(KeyEvent e){
            char c = e.getKeyChar();
            if (!Character.isDigit(c)) {
                e.consume();
            }
        }
        });
        
        jTextField1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
            Otomatis();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                Otomatis();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                Otomatis();
            }
        
        });
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void SatuanComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SatuanComboBox1ItemStateChanged
        // TODO add your handling code here:
        

    }//GEN-LAST:event_SatuanComboBox1ItemStateChanged

        private void   updateRadioButtons(String Unit){
            switch (Unit) {
                case "Celcius":
                    jRadioButton1.setText("Celcius ke  Fahrenheit ");
                    jRadioButton2.setText("Celcius ke  Reamur ");
                    jRadioButton3.setText("Celcius ke  Kelvin");
                    break;
                 case "Fahrenheit" :
                    jRadioButton1.setText("Fahrenheit ke  Celcius ");
                    jRadioButton2.setText("Fahrenheit ke  Reamur ");
                    jRadioButton3.setText("Fahrenheit ke  Kelvin");
                    break;
                    case "Reamur" :
                    jRadioButton1.setText("Reamur ke  Celcius ");
                    jRadioButton2.setText("Reamur ke  Fahrenheit ");
                    jRadioButton3.setText("Reamur ke  Kelvin");
                    break;
                    case "Kelvin" :
                    jRadioButton1.setText("Kelvin ke  Celcius ");
                    jRadioButton2.setText("Kelvin ke  Fahrenheit ");
                    jRadioButton3.setText("Kelvin ke  Reamur");
                    break;
                default:
                    throw new AssertionError();
            }
        }
        
        private void Otomatis(){
            try {
                String input = jTextField1.getText();
            if (input.isEmpty()) {
                jLabel3.setText("Hasil Konversi             : ");
                return;
            }
            double suhuAwal,hasil;
        hasil = 0;
        suhuAwal = Double.parseDouble(jTextField1.getText());
        
        if (jRadioButton1.isSelected()) {
            if (jRadioButton1.getText().contains("Celcius ke  Fahrenheit ")) {
                hasil= suhuAwal*9/5+32;
            }else if (jRadioButton1.getText().contains("Fahrenheit ke  Celcius ")) {
                hasil = (suhuAwal-32)*5/9;
            }else if (jRadioButton1.getText().contains("Reamur ke  Celcius ")) {
                hasil = suhuAwal*5/4;
            }else if (jRadioButton1.getText().contains("Kelvin ke  Celcius")) {
                hasil = suhuAwal-2731.15;
            }
            
        }else if (jRadioButton2.isSelected()) {
            if (jRadioButton2.getText().contains("Celcius ke  Reamur ")) {
                hasil= suhuAwal*4/5;
            }else if (jRadioButton2.getText().contains("Fahrenheit ke  Reamur ")) {
                hasil = (suhuAwal-32)*4/9;
            }else if (jRadioButton2.getText().contains("Reamur ke  Fahrenheit ")) {
                hasil = suhuAwal*9/4+32;
            }else if (jRadioButton2.getText().contains("Kelvin ke  Fahrenheit")) {
                hasil = (suhuAwal-273.15)*9/5+32;
            }
        }else if (jRadioButton3.isSelected()) {
             if (jRadioButton3.getText().contains("Celcius ke  Kelvin")) {
                hasil= suhuAwal+273.15;
            }else if (jRadioButton3.getText().contains("Fahrenheit ke  Kelvin ")) {
                hasil = (suhuAwal-32)*5/9+273.15;
            }else if (jRadioButton3.getText().contains("Reamur ke  Kelvin ")) {
                hasil = suhuAwal*5/4+273.15;
            }else if (jRadioButton3.getText().contains("Kelvin ke  Reamur")) {
                hasil = (suhuAwal-273.15)*4/5;
            }
            
        }
        
        jTextField2.setText(String.format("%.2f",hasil));
            } catch (Exception e) {
            }
            
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SatuanComboBox1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
